### ISSUE TITLE
vk.com 

### ISSUE THREAD

**Issue by TrueMax** [SimplicityMobile/Simplicity#3]
If their API is not well-documented in English, I can help.

**Comment by edjiang** [comment]
Cool, looks like it should be pretty straightforward since they support the implicit flow for native clients: http://vk.com/dev/auth_mobile

You might even be able to use it right now by creating a generic OAuth 2 Provider object. Documentation here: http://cocoadocs.org/docsets/Simplicity/1.0/Classes/OAuth2.html

**Comment by edjiang** [comment]
VK is live on Cocoapods under `1.0.2`!

Keep in mind with the new cocoapods, you might have to manually `pod update` to see the new version. 

```Swift
Simplicity.login(VKontakte()) { (accessToken, error) in
  // Handle access token here
}
```
